name: app3
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_riverpod: ^2.4.9
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.5
  flutter_svg_provider: ^1.0.3
  intl: ^0.18.0
  animations: ^2.0.8
  riverpod_annotation: ^2.3.3
  flutter_screenutil: ^5.9.0
  dot_navigation_bar: ^1.0.2
dev_dependencies: 
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_test: 
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Alegreya
      fonts: 
        - asset: assets/fonts/AlegreyaBold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaMedium.ttf
          weight: 500
    - family: Alegreya Sans
      fonts: 
        - asset: assets/fonts/AlegreyaSansMedium.ttf
          weight: 500
        - asset: assets/fonts/AlegreyaSansRegular.ttf
          weight: 400
        - asset: assets/fonts/AlegreyaSansBold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSansLight.ttf
          weight: 300
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
    - family: Karla
      fonts: 
        - asset: assets/fonts/KarlaRegular.ttf
          weight: 400
